name: Core Predict (Core+++ stable)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "30 06 * * *"
    - cron: "30 22 * * SAT"
    - cron: "30 22 * * SUN"
    - cron: "30 08 * * MON"

permissions:
  contents: write
  pull-requests: write

jobs:
  core:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    concurrency:
      group: core-predict
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch FD results
        env:
          FOOTBALL_DATA_TOKEN: ${{ secrets.FOOTBALL_DATA_TOKEN }}
          FD_COMP: PL
          FD_SEASONS: "2024,2025"
        run: python -m scripts.core_fetch

      - name: Build ratings (decay + opponent-adjust + Elo)
        env:
          HALF_LIFE_DAYS: "180"
        run: python -m scripts.core_build_ratings

      - name: Generate predictions (14d window, blended 1X2)
        env:
          FOOTBALL_DATA_TOKEN: ${{ secrets.FOOTBALL_DATA_TOKEN }}
          FD_COMP: PL
          FD_WINDOW_DAYS: "14"
          FD_STATUSES: "SCHEDULED,TIMED"
          BLEND_ELO: "0.40"
        run: python -m scripts.core_generate

      - name: Create PR (auto-merge)
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "auto/core-${{ github.run_id }}"
          title: "Core+++ predictions update – ${{ github.run_id }}"
          body: |
            Updated outputs:
            - data/fd_results.csv
            - data/team_strengths.json
            - data/elo_ratings.json
            - data/predictions.json
          commit-message: "chore(core+++): update predictions"
          delete-branch: true
          merge: true
          merge-method: squash
