name: Core Predict (PR)

on:
  workflow_dispatch:
  schedule:
    - cron: "45 6 * * *"   # daily 06:45 UTC
  push:
    paths:
      - plpred/**
      - scripts/generate.py
      - requirements.txt
      - .github/workflows/core_predict_pr.yml

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: core-predict-pr
  cancel-in-progress: false

jobs:
  predict:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate (CORE)
        env:
          PYTHONPATH: ${{ github.workspace }}
          FOOTBALL_DATA_TOKEN: ${{ secrets.FOOTBALL_DATA_TOKEN }}
        run: |
          python -u scripts/generate.py

      - name: Detect changes
        id: diff
        run: |
          git status --porcelain data reports > changed.txt || true
          lines=$(wc -l < changed.txt | tr -d ' ')
          if [ "$lines" -gt 0 ]; then
            echo "changed=true"  >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi
          echo "---- changed files ----"
          cat changed.txt || true

      - name: Create Pull Request
        if: steps.diff.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "core/update-${{ github.run_id }}"
          commit-message: "chore(core): update predictions"
          title: "Core predictions update (#${{ github.run_number }})"
          body: |
            Auto-generated update from workflow run ${{ github.run_id }}.
          delete-branch: true
          add-paths: |
            data/**
            reports/**

      - name: Show PR URL (if any)
        if: steps.diff.outputs.changed == 'true'
        run: echo "PR created (if any) — check the Pull Requests tab."

